### ISSUE TITLE
Sensor is broken with HA 2024.5

### ISSUE THREAD

**Issue by marcusboon** [vasqued2/ha-teamtracker#151]
Updated HA to 2024.5 this morning and noticed that Teamtracker seems to be broken. None of the sensors provided by TeamTracker are working and the logs seem to indicate some issue

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:356
integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 8:13:27 AM (50 occurrences)
Last logged: 8:13:27 AM

Error while setting up teamtracker platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/teamtracker/sensor.py", line 118, in async_setup_platform
    config.entry_id = slugify(f"{config.get(CONF_TEAM_ID)}")
    ^^^^^^^^^^^^^^^
AttributeError: 'NodeDictClass' object has no attribute 'entry_id'
```

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:356
integration: Sensor (documentation, issues)
First occurred: 8:13:27 AM (1 occurrences)
Last logged: 8:13:27 AM

Error while setting up teamtracker platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/teamtracker/sensor.py", line 115, in async_setup_platform
    config.entry_id = slugify(f"{config.get(CONF_TEAM_ID)}")
    ^^^^^^^^^^^^^^^
AttributeError: 'NodeDictClass' object has no attribute 'entry_id'
```

**Comment by compoundbow83** [comment]
same here all sensores from the teams are unavailble after update HA to 2024.5.0

**Comment by talsayon** [comment]
Same issue

**Comment by schumi2309** [comment]
you will probably have to wait for an update from Teamtracker!
Patience friends...

**Comment by NRutt2005** [comment]
@marcusboon @compoundbow83 @talsayon, I was having the same issue however I was able to get this issue fixed. Do you have custom sensors for this integration configured through the HA configuration file? I did have an issue with my college softball and college baseball. I deleted those sensors from my configuration file and deleted the sensor entities from the Team Tracker integration. I then restarted home assistant then re-added the these entities but thought the GUI. See the attached screenshots. 

I hope this helps you out.

<img width="623" alt="Screenshot 2024-05-05 at 15 55 29" src="https://github.com/vasqued2/ha-teamtracker/assets/75466468/b32f4960-d14f-40d6-b8c4-010df3d516d7">
<img width="609" alt="Screenshot 2024-05-05 at 15 56 06" src="https://github.com/vasqued2/ha-teamtracker/assets/75466468/fcdda827-4b62-46fb-9559-fca7fbe9438b">

**Comment by JeffCrum1** [comment]
Yeah, Mine are all 'normal' sensors.  I am hoping we don't have to do this.

I expect @vasqued2 will fix this as soon as possible and we won't have to go through hoops.

**Comment by schumi2309** [comment]
Me too.

**Comment by compoundbow83** [comment]
> @marcusboon @compoundbow83 @talsayon, I was having the same issue however I was able to get this issue fixed. Do you have custom sensors for this integration configured through the HA configuration file? I did have an issue with my college softball and college baseball. I deleted those sensors from my configuration file and deleted the sensor entities from the Team Tracker integration. I then restarted home assistant then re-added the these entities but thought the GUI. See the attached screenshots.
> 
> I hope this helps you out.
> 
> <img alt="Screenshot 2024-05-05 at 15 55 29" width="623" src="https://private-user-images.githubusercontent.com/75466468/328049366-b32f4960-d14f-40d6-b8c4-010df3d516d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMTQ4NjYsIm5iZiI6MTcxNTAxNDU2NiwicGF0aCI6Ii83NTQ2NjQ2OC8zMjgwNDkzNjYtYjMyZjQ5NjAtZDE0Zi00MGQ2LWI4YzQtMDEwZGYzZDUxNmQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDE2NTYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlZWVlMThlMTVhNGRhZTZkZTI0NDk0YmFmMDBiYzlkYmZmY2M0OTM3N2YyMzY1YmViYmIzYWIxYjYxYTkwZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8PDb_DkmaQpZx4j0KNRLdwMjgM8HwXJdfm1ZADo-zEE"> <img alt="Screenshot 2024-05-05 at 15 56 06" width="609" src="https://private-user-images.githubusercontent.com/75466468/328049373-fcdda827-4b62-46fb-9559-fca7fbe9438b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMTQ4NjYsIm5iZiI6MTcxNTAxNDU2NiwicGF0aCI6Ii83NTQ2NjQ2OC8zMjgwNDkzNzMtZmNkZGE4MjctNGI2Mi00NmZiLTk1NTktZmNhN2ZiZTk0MzhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDE2NTYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmZjc3ODUwYWQ0NDk5NTMxZTZiZDUxM2RlMDk5ZjJjOGE2ZTJkZGQ4OTk2OGE4M2JkMmE5NmZlY2IxMjljNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TMwEhrlT0IJP4A5fr_z2VvcqmojX_0bozJwneSCdikM">

Thank you. I does now the same way. Deleted the sensors in the config, Deleted the sensors from teamtracker. After this restart HA und add the teams over the gui. Now it works again.

**Comment by vasqued2** [comment]
Sorry, haven't upgraded yet so didn't notice.  I'll dig into it tomorrow.

**Comment by deboy69** [comment]
@vasqued2 any luck finding the cause of the error?

**Comment by vasqued2** [comment]
The issue was in code that was in the original nfl sensor this was based on.  As such, I didn't fully understand what it was trying to do as it had always just worked.  I was finally able to develop a fix that works for me and I don't believe it has any unintended side effects, which was one of my concerns without fully understanding why the original code was the way it was.

I have released it as a beta version.  If you Redownload from HACS and select "Show beta versions" you should get the option to download `version v0.12.0.beta`.  Try that.

Assuming it's stable for me today and I don't hear any issues from others, I will release it widespread tomorrow.  If you try it, let me know if it works or you still have the issue.

**Comment by JeffCrum1** [comment]
Looking good for me.  Thanks for fixing it.

**Comment by schumi2309** [comment]
Good for me too. 
Thank you. You are the best 😉

**Comment by marcusboon** [comment]
+1 can confirm, the fix works for me and the sensors are back now with the v0.12.0.beta version

**Comment by vasqued2** [comment]
Released v0.12.0 which should fix the issue.
